-- =============================================================================
-- Migration: create_tasks_table
--
-- Creates the `public.tasks` table and locks it down with Row Level Security.
--
-- Why this is a migration file (and not something clicked in the dashboard):
--   Migrations are the version-controlled history of your schema. Every
--   environment (local, staging, production) gets the same schema by
--   replaying these files in timestamp order with `supabase db push`
--   (or `supabase db reset` locally).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. The table
-- -----------------------------------------------------------------------------
create table public.tasks (
  -- UUID primary key generated by Postgres. UUIDs (vs serial integers) are
  -- safe to expose to clients: ids can't be guessed by incrementing.
  id          uuid        primary key default gen_random_uuid(),

  -- Foreign key to Supabase Auth's users table. `auth.users` lives in the
  -- `auth` schema, which Supabase Auth (GoTrue) manages for you.
  --
  -- DEFAULT auth.uid(): when the mobile app inserts a task without a user_id,
  -- Postgres fills it with the id from the caller's JWT. The client never has
  -- to (and should never be trusted to) say who it is.
  --
  -- ON DELETE CASCADE: deleting a user deletes their tasks.
  user_id     uuid        not null default auth.uid()
                          references auth.users (id) on delete cascade,

  -- Business rule enforced in the database, not only in the UI: a title must
  -- contain at least one non-whitespace character and be at most 200 chars.
  title       text        not null
                          check (char_length(btrim(title)) between 1 and 200),

  completed   boolean     not null default false,

  -- Always use timestamptz (timestamp WITH time zone) in Postgres. It stores
  -- an absolute instant (UTC) and avoids time-zone bugs.
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.tasks is 'A to-do item owned by exactly one authenticated user.';

-- The app always asks for "my tasks, newest first". This index serves that
-- query directly, and also makes the RLS check (user_id = auth.uid()) cheap.
create index tasks_user_id_created_at_idx
  on public.tasks (user_id, created_at desc);


-- -----------------------------------------------------------------------------
-- 2. Keep updated_at correct automatically
--
-- A trigger runs inside Postgres on every UPDATE, so updated_at is correct no
-- matter who changes the row (mobile app, Edge Function, SQL editor...).
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
-- Pin search_path so the function can't be tricked into resolving names
-- against a schema an attacker controls (Supabase's linter flags this).
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger tasks_set_updated_at
  before update on public.tasks
  for each row
  execute function public.set_updated_at();


-- -----------------------------------------------------------------------------
-- 3. Table privileges (GRANTs)
--
-- Postgres has two layers of access control:
--   a) GRANTs   — "may this ROLE touch this TABLE at all?"
--   b) RLS      — "which ROWS may this request see/change?"
--
-- Supabase's API connects as one of these Postgres roles:
--   anon           — request carries no user JWT (signed out)
--   authenticated  — request carries a valid user JWT (signed in)
--   service_role   — secret/service key; BYPASSES RLS. Server-side only!
--
-- We grant explicitly so the intent is obvious, and give `anon` nothing:
-- signed-out users have no business with tasks.
-- -----------------------------------------------------------------------------
revoke all on table public.tasks from anon;
grant select, insert, update, delete on table public.tasks to authenticated;


-- -----------------------------------------------------------------------------
-- 4. Row Level Security
--
-- Once RLS is enabled, a role that is not exempt (anon, authenticated) sees
-- ZERO rows until a policy allows it. RLS is "deny by default".
--
-- Every policy below has the same shape:
--   for <command>        which SQL command it applies to
--   to authenticated     which Postgres role it applies to
--   using (...)          filter on EXISTING rows (SELECT/UPDATE/DELETE)
--   with check (...)     validation of NEW row values (INSERT/UPDATE)
--
-- auth.uid() returns the `sub` claim of the JWT on the current request, i.e.
-- the signed-in user's id. It's wrapped in (select ...) so Postgres evaluates
-- it once per query instead of once per row — a documented Supabase
-- performance best practice.
-- -----------------------------------------------------------------------------
alter table public.tasks enable row level security;

-- SELECT: you can only read rows you own. Other users' rows are not
-- "forbidden" — they're simply invisible, as if they didn't exist.
create policy "Users can view their own tasks"
  on public.tasks
  for select
  to authenticated
  using ( (select auth.uid()) = user_id );

-- INSERT: the NEW row must belong to you. If a client sends
-- user_id = '<someone else>', Postgres rejects the insert with
-- "new row violates row-level security policy".
create policy "Users can create their own tasks"
  on public.tasks
  for insert
  to authenticated
  with check ( (select auth.uid()) = user_id );

-- UPDATE: `using` decides which rows you can target (only yours);
-- `with check` stops you from changing user_id to give a task away.
create policy "Users can update their own tasks"
  on public.tasks
  for update
  to authenticated
  using      ( (select auth.uid()) = user_id )
  with check ( (select auth.uid()) = user_id );

-- DELETE: you can only delete rows you own. Deleting someone else's id
-- silently affects 0 rows (the row is invisible to you).
create policy "Users can delete their own tasks"
  on public.tasks
  for delete
  to authenticated
  using ( (select auth.uid()) = user_id );
